name: kids_learning_app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  equatable: 2.0.5
  go_router: 13.2.0
  sqflite: 2.3.2
  path_provider: 2.1.2
  audioplayers: 5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/alphabet/
    - assets/images/numbers/
    - assets/images/colors/
    - assets/images/shapes/
    - assets/images/animals/
    - assets/images/foods/
    - assets/audio/pronunciations/
    - assets/audio/rhymes/
