name: reading_app
version: 1.0.0+1
description: Premium Flutter Reading App
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/books.json
